return {
  require("custom.plugins.whichkey"),
  require("custom.plugins.snacks-indent"),
  require("custom.plugins.live-preview"),
  require("custom.plugins.snacks-picker"),
  require("custom.plugins.neo-tree"),
  require("custom.plugins.tmux-navigator"),
  require("custom.plugins.precognition"),
  require("custom.plugins.cord"),
  require("custom.plugins.user"),
  require("custom.plugins.harpoon"),
  require("custom.plugins.oil"),
  require("custom.plugins.mini-files"),
  require("custom.plugins.disable.disable"),
  require("custom.plugins.base46"),
  require("custom.plugins.blink-cmp"),
  require("custom.plugins.octo"),
}
