cursor #2e3440
cursor_text_color #3b4252

foreground            #2e3440
background            #e5e9f0
selection_foreground  #e5e9f0
selection_background  #97365b
url_color             #3b6ea8

color0   #3b4252
color1   #9f2348
color2   #137e22
color3   #c9bf05
color4   #3870b0
color5   #cae2ff
color6   #3b6ea8
color7   #2c2d2f
color8   #8a8c8e
color9   #e15d81
color10  #34b846
color11  #dad014
color12  #528cd8
color13  #cae2ff
color14  #93b4da
color15  #f5f8fc
