cursor #e7e1e5
cursor_text_color #cdc3ce

foreground            #e7e1e5
background            #151316
selection_foreground  #372c3e
selection_background  #d2c1d8
url_color             #dbbbef

color0   #151316
color1   #ff728a
color2   #77ef94
color3   #ffdc72
color4   #cca7e3
color5   #5d426e
color6   #dbbbef
color7   #f5ebfa
color8   #968f9b
color9   #ff9faf
color10  #a5ffbb
color11  #ffe8a5
color12  #eccfff
color13  #f0d8ff
color14  #f5e6ff
color15  #fcf8ff
